apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-round-robin
  namespace: sample
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
