apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: vks-antrea01-antrea
  namespace: test-ns
spec:
  values:
    antrea:
      config:
        featureGates:
    antreaNSX:
      enable: true
