apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: vks-calico01-calico           <clustername>-calico
  namespace: test-ns
spec:
  values:
    calico:
      config:
        vethMTU: 0
